name: Main workflow
on:
  pull_request:
  push:
    branches:
      - yc/**
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: macOS-latest
    timeout-minutes: 10
    strategy:
      matrix:
        api-level: [21, 23, 29]
        java-version: [9, 10, 11, 12 ,13]
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build, test and lint
      run: |
        npm install
        npm run build
        npm run lint
        npm test

    - name: Prepare test fixture
      run: cp -a ./test-fixture/* ./

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: run action
      uses: ./
      with:
        api-level: 23
        target: google_apis
        arch: x86
        profile: Nexus 6
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        # script: |
        #   ./gradlew help
        #   ./gradlew connectedDebugAndroidTest
